{
    'name': 'school_student',
    'description': 'School Student',
    'version': '1.3',
    'author': 'Annoynse',
    'summary': 'eduction,sport,free learning',
    'sequence': '1',
    'depends': ['base', 'mail','owl_js'],
    'category': 'Eduction',
    'website': 'https://www.odoo.com/app/school_student',
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_student.xml',
        # 'data/eamil_template.csv',
        # 'data/templat_school_student.xml',
        # 'data/data_school_student.xml',
        'wizard/class_start_wizard.xml',
        'views/views_school_student_views.xml',
        'views/views_school_student_menu.xml',
        'views/view_student_teacher.xml',
        'views/views_school_teacher_menu.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
