from . import project_team_member
from . import res_state_city
from . import hr_timesheet
from . import res_users_inherit
from . import project_team
from . import add_member_wizard
from . import project_project_inherit
from . import project_task_inherit
from . import set_task_priority
from . import res_country_state